[package]
name = "av-wav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.0"
av-data = "0.4"
av-format = "0.5.0"

[profile.release]
strip = "debuginfo"
